import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modSidebar: [{type: 'autogenerated', dirName: 'mods'}],
  
  oneBlockSidebar: [{type: 'autogenerated', dirName: 'oneblock'}],
};

export default sidebars;
