import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modSidebar: [{type: 'autogenerated', dirName: 'mods'}],
  survivalSidebar: [{type: 'autogenerated', dirName: 'survival'}],
};

export default sidebars;
